// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type File struct {
	ID        string `json:"id"`
	SessionID string `json:"session_id"`
	Path      string `json:"path"`
	Content   string `json:"content"`
	Version   int64  `json:"version"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type FileMetadatum struct {
	Path         string         `json:"path"`
	Language     string         `json:"language"`
	LastParsedAt sql.NullInt64  `json:"last_parsed_at"`
	Checksum     sql.NullString `json:"checksum"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type Message struct {
	ID         string         `json:"id"`
	SessionID  string         `json:"session_id"`
	Role       string         `json:"role"`
	Parts      string         `json:"parts"`
	Model      sql.NullString `json:"model"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
	Provider   sql.NullString `json:"provider"`
}

type Relationship struct {
	ID           string `json:"id"`
	FromSymbolID string `json:"from_symbol_id"`
	ToSymbolID   string `json:"to_symbol_id"`
	Type         string `json:"type"`
	Line         int64  `json:"line"`
	Column       int64  `json:"column"`
	CreatedAt    int64  `json:"created_at"`
}

type Session struct {
	ID               string         `json:"id"`
	ParentSessionID  sql.NullString `json:"parent_session_id"`
	Title            string         `json:"title"`
	MessageCount     int64          `json:"message_count"`
	PromptTokens     int64          `json:"prompt_tokens"`
	CompletionTokens int64          `json:"completion_tokens"`
	Cost             float64        `json:"cost"`
	UpdatedAt        int64          `json:"updated_at"`
	CreatedAt        int64          `json:"created_at"`
	SummaryMessageID sql.NullString `json:"summary_message_id"`
}

type Symbol struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Type       string         `json:"type"`
	FilePath   string         `json:"file_path"`
	Line       int64          `json:"line"`
	Column     int64          `json:"column"`
	Scope      sql.NullString `json:"scope"`
	Visibility sql.NullString `json:"visibility"`
	ReturnType sql.NullString `json:"return_type"`
	Parameters sql.NullString `json:"parameters"`
	ParentID   sql.NullString `json:"parent_id"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}
