// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFileMetadata(ctx context.Context, arg CreateFileMetadataParams) (FileMetadatum, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSymbol(ctx context.Context, arg CreateSymbolParams) (Symbol, error)
	DeleteFile(ctx context.Context, id string) error
	DeleteFileMetadata(ctx context.Context, path string) error
	DeleteMessage(ctx context.Context, id string) error
	DeleteRelationship(ctx context.Context, id string) error
	DeleteRelationshipsByFile(ctx context.Context, arg DeleteRelationshipsByFileParams) error
	DeleteRelationshipsBySymbol(ctx context.Context, arg DeleteRelationshipsBySymbolParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionFiles(ctx context.Context, sessionID string) error
	DeleteSessionMessages(ctx context.Context, sessionID string) error
	DeleteSymbol(ctx context.Context, id string) error
	DeleteSymbolsByFile(ctx context.Context, filePath string) error
	GetFile(ctx context.Context, id string) (File, error)
	GetFileByPathAndSession(ctx context.Context, arg GetFileByPathAndSessionParams) (File, error)
	GetFileMetadata(ctx context.Context, path string) (FileMetadatum, error)
	GetMessage(ctx context.Context, id string) (Message, error)
	GetRelationship(ctx context.Context, id string) (Relationship, error)
	GetSessionByID(ctx context.Context, id string) (Session, error)
	GetSymbol(ctx context.Context, id string) (Symbol, error)
	ListFileMetadata(ctx context.Context) ([]FileMetadatum, error)
	ListFilesByPath(ctx context.Context, path string) ([]File, error)
	ListFilesBySession(ctx context.Context, sessionID string) ([]File, error)
	ListLatestSessionFiles(ctx context.Context, sessionID string) ([]File, error)
	ListMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	ListNewFiles(ctx context.Context) ([]File, error)
	ListRelationshipsByFile(ctx context.Context, arg ListRelationshipsByFileParams) ([]Relationship, error)
	ListRelationshipsBySymbol(ctx context.Context, arg ListRelationshipsBySymbolParams) ([]Relationship, error)
	ListRelationshipsByType(ctx context.Context, type_ string) ([]Relationship, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListSymbolsByFile(ctx context.Context, filePath string) ([]Symbol, error)
	ListSymbolsByName(ctx context.Context, name string) ([]Symbol, error)
	ListSymbolsByType(ctx context.Context, type_ string) ([]Symbol, error)
	UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) error
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateSymbol(ctx context.Context, arg UpdateSymbolParams) error
}

var _ Querier = (*Queries)(nil)
