// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: symbols.sql

package db

import (
	"context"
	"database/sql"
)

const createFileMetadata = `-- name: CreateFileMetadata :one
INSERT INTO file_metadata (
    path,
    language,
    last_parsed_at,
    checksum,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING path, language, last_parsed_at, checksum, created_at, updated_at
`

type CreateFileMetadataParams struct {
	Path         string         `json:"path"`
	Language     string         `json:"language"`
	LastParsedAt sql.NullInt64  `json:"last_parsed_at"`
	Checksum     sql.NullString `json:"checksum"`
}

func (q *Queries) CreateFileMetadata(ctx context.Context, arg CreateFileMetadataParams) (FileMetadatum, error) {
	row := q.db.QueryRowContext(ctx, createFileMetadata,
		arg.Path,
		arg.Language,
		arg.LastParsedAt,
		arg.Checksum,
	)
	var i FileMetadatum
	err := row.Scan(
		&i.Path,
		&i.Language,
		&i.LastParsedAt,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO relationships (
    id,
    from_symbol_id,
    to_symbol_id,
    type,
    line,
    column,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, strftime('%s', 'now')
)
RETURNING id, from_symbol_id, to_symbol_id, type, line, "column", created_at
`

type CreateRelationshipParams struct {
	ID           string `json:"id"`
	FromSymbolID string `json:"from_symbol_id"`
	ToSymbolID   string `json:"to_symbol_id"`
	Type         string `json:"type"`
	Line         int64  `json:"line"`
	Column       int64  `json:"column"`
}

func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error) {
	row := q.db.QueryRowContext(ctx, createRelationship,
		arg.ID,
		arg.FromSymbolID,
		arg.ToSymbolID,
		arg.Type,
		arg.Line,
		arg.Column,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.FromSymbolID,
		&i.ToSymbolID,
		&i.Type,
		&i.Line,
		&i.Column,
		&i.CreatedAt,
	)
	return i, err
}

const createSymbol = `-- name: CreateSymbol :one
INSERT INTO symbols (
    id,
    name,
    type,
    file_path,
    line,
    column,
    scope,
    visibility,
    return_type,
    parameters,
    parent_id,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%s', 'now'), strftime('%s', 'now')
)
RETURNING id, name, type, file_path, line, "column", scope, visibility, return_type, parameters, parent_id, created_at, updated_at
`

type CreateSymbolParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Type       string         `json:"type"`
	FilePath   string         `json:"file_path"`
	Line       int64          `json:"line"`
	Column     int64          `json:"column"`
	Scope      sql.NullString `json:"scope"`
	Visibility sql.NullString `json:"visibility"`
	ReturnType sql.NullString `json:"return_type"`
	Parameters sql.NullString `json:"parameters"`
	ParentID   sql.NullString `json:"parent_id"`
}

func (q *Queries) CreateSymbol(ctx context.Context, arg CreateSymbolParams) (Symbol, error) {
	row := q.db.QueryRowContext(ctx, createSymbol,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.FilePath,
		arg.Line,
		arg.Column,
		arg.Scope,
		arg.Visibility,
		arg.ReturnType,
		arg.Parameters,
		arg.ParentID,
	)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.FilePath,
		&i.Line,
		&i.Column,
		&i.Scope,
		&i.Visibility,
		&i.ReturnType,
		&i.Parameters,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFileMetadata = `-- name: DeleteFileMetadata :exec
DELETE FROM file_metadata
WHERE path = ?
`

func (q *Queries) DeleteFileMetadata(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteFileMetadata, path)
	return err
}

const deleteRelationship = `-- name: DeleteRelationship :exec
DELETE FROM relationships
WHERE id = ?
`

func (q *Queries) DeleteRelationship(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRelationship, id)
	return err
}

const deleteRelationshipsByFile = `-- name: DeleteRelationshipsByFile :exec
DELETE FROM relationships
WHERE from_symbol_id IN (
    SELECT s.id FROM symbols s WHERE s.file_path = ?
) OR to_symbol_id IN (
    SELECT s.id FROM symbols s WHERE s.file_path = ?
)
`

type DeleteRelationshipsByFileParams struct {
	FilePath   string `json:"file_path"`
	FilePath_2 string `json:"file_path_2"`
}

func (q *Queries) DeleteRelationshipsByFile(ctx context.Context, arg DeleteRelationshipsByFileParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelationshipsByFile, arg.FilePath, arg.FilePath_2)
	return err
}

const deleteRelationshipsBySymbol = `-- name: DeleteRelationshipsBySymbol :exec
DELETE FROM relationships
WHERE from_symbol_id = ? OR to_symbol_id = ?
`

type DeleteRelationshipsBySymbolParams struct {
	FromSymbolID string `json:"from_symbol_id"`
	ToSymbolID   string `json:"to_symbol_id"`
}

func (q *Queries) DeleteRelationshipsBySymbol(ctx context.Context, arg DeleteRelationshipsBySymbolParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelationshipsBySymbol, arg.FromSymbolID, arg.ToSymbolID)
	return err
}

const deleteSymbol = `-- name: DeleteSymbol :exec
DELETE FROM symbols
WHERE id = ?
`

func (q *Queries) DeleteSymbol(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSymbol, id)
	return err
}

const deleteSymbolsByFile = `-- name: DeleteSymbolsByFile :exec
DELETE FROM symbols
WHERE file_path = ?
`

func (q *Queries) DeleteSymbolsByFile(ctx context.Context, filePath string) error {
	_, err := q.db.ExecContext(ctx, deleteSymbolsByFile, filePath)
	return err
}

const getFileMetadata = `-- name: GetFileMetadata :one
SELECT path, language, last_parsed_at, checksum, created_at, updated_at
FROM file_metadata
WHERE path = ? LIMIT 1
`

func (q *Queries) GetFileMetadata(ctx context.Context, path string) (FileMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getFileMetadata, path)
	var i FileMetadatum
	err := row.Scan(
		&i.Path,
		&i.Language,
		&i.LastParsedAt,
		&i.Checksum,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelationship = `-- name: GetRelationship :one
SELECT id, from_symbol_id, to_symbol_id, type, line, "column", created_at
FROM relationships
WHERE id = ? LIMIT 1
`

func (q *Queries) GetRelationship(ctx context.Context, id string) (Relationship, error) {
	row := q.db.QueryRowContext(ctx, getRelationship, id)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.FromSymbolID,
		&i.ToSymbolID,
		&i.Type,
		&i.Line,
		&i.Column,
		&i.CreatedAt,
	)
	return i, err
}

const getSymbol = `-- name: GetSymbol :one
SELECT id, name, type, file_path, line, "column", scope, visibility, return_type, parameters, parent_id, created_at, updated_at
FROM symbols
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSymbol(ctx context.Context, id string) (Symbol, error) {
	row := q.db.QueryRowContext(ctx, getSymbol, id)
	var i Symbol
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.FilePath,
		&i.Line,
		&i.Column,
		&i.Scope,
		&i.Visibility,
		&i.ReturnType,
		&i.Parameters,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFileMetadata = `-- name: ListFileMetadata :many
SELECT path, language, last_parsed_at, checksum, created_at, updated_at
FROM file_metadata
ORDER BY updated_at DESC
`

func (q *Queries) ListFileMetadata(ctx context.Context) ([]FileMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listFileMetadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileMetadatum{}
	for rows.Next() {
		var i FileMetadatum
		if err := rows.Scan(
			&i.Path,
			&i.Language,
			&i.LastParsedAt,
			&i.Checksum,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsByFile = `-- name: ListRelationshipsByFile :many
SELECT r.id, r.from_symbol_id, r.to_symbol_id, r.type, r.line, r."column", r.created_at
FROM relationships r
WHERE r.from_symbol_id IN (
    SELECT s.id FROM symbols s WHERE s.file_path = ?
) OR r.to_symbol_id IN (
    SELECT s.id FROM symbols s WHERE s.file_path = ?
)
`

type ListRelationshipsByFileParams struct {
	FilePath   string `json:"file_path"`
	FilePath_2 string `json:"file_path_2"`
}

func (q *Queries) ListRelationshipsByFile(ctx context.Context, arg ListRelationshipsByFileParams) ([]Relationship, error) {
	rows, err := q.db.QueryContext(ctx, listRelationshipsByFile, arg.FilePath, arg.FilePath_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Relationship{}
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.FromSymbolID,
			&i.ToSymbolID,
			&i.Type,
			&i.Line,
			&i.Column,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsBySymbol = `-- name: ListRelationshipsBySymbol :many
SELECT id, from_symbol_id, to_symbol_id, type, line, "column", created_at
FROM relationships
WHERE from_symbol_id = ? OR to_symbol_id = ?
ORDER BY created_at ASC
`

type ListRelationshipsBySymbolParams struct {
	FromSymbolID string `json:"from_symbol_id"`
	ToSymbolID   string `json:"to_symbol_id"`
}

func (q *Queries) ListRelationshipsBySymbol(ctx context.Context, arg ListRelationshipsBySymbolParams) ([]Relationship, error) {
	rows, err := q.db.QueryContext(ctx, listRelationshipsBySymbol, arg.FromSymbolID, arg.ToSymbolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Relationship{}
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.FromSymbolID,
			&i.ToSymbolID,
			&i.Type,
			&i.Line,
			&i.Column,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsByType = `-- name: ListRelationshipsByType :many
SELECT id, from_symbol_id, to_symbol_id, type, line, "column", created_at
FROM relationships
WHERE type = ?
ORDER BY created_at ASC
`

func (q *Queries) ListRelationshipsByType(ctx context.Context, type_ string) ([]Relationship, error) {
	rows, err := q.db.QueryContext(ctx, listRelationshipsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Relationship{}
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.FromSymbolID,
			&i.ToSymbolID,
			&i.Type,
			&i.Line,
			&i.Column,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymbolsByFile = `-- name: ListSymbolsByFile :many
SELECT id, name, type, file_path, line, "column", scope, visibility, return_type, parameters, parent_id, created_at, updated_at
FROM symbols
WHERE file_path = ?
ORDER BY line ASC, column ASC
`

func (q *Queries) ListSymbolsByFile(ctx context.Context, filePath string) ([]Symbol, error) {
	rows, err := q.db.QueryContext(ctx, listSymbolsByFile, filePath)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Symbol{}
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.FilePath,
			&i.Line,
			&i.Column,
			&i.Scope,
			&i.Visibility,
			&i.ReturnType,
			&i.Parameters,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymbolsByName = `-- name: ListSymbolsByName :many
SELECT id, name, type, file_path, line, "column", scope, visibility, return_type, parameters, parent_id, created_at, updated_at
FROM symbols
WHERE name = ?
ORDER BY file_path ASC, line ASC
`

func (q *Queries) ListSymbolsByName(ctx context.Context, name string) ([]Symbol, error) {
	rows, err := q.db.QueryContext(ctx, listSymbolsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Symbol{}
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.FilePath,
			&i.Line,
			&i.Column,
			&i.Scope,
			&i.Visibility,
			&i.ReturnType,
			&i.Parameters,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSymbolsByType = `-- name: ListSymbolsByType :many
SELECT id, name, type, file_path, line, "column", scope, visibility, return_type, parameters, parent_id, created_at, updated_at
FROM symbols
WHERE type = ?
ORDER BY file_path ASC, line ASC
`

func (q *Queries) ListSymbolsByType(ctx context.Context, type_ string) ([]Symbol, error) {
	rows, err := q.db.QueryContext(ctx, listSymbolsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Symbol{}
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.FilePath,
			&i.Line,
			&i.Column,
			&i.Scope,
			&i.Visibility,
			&i.ReturnType,
			&i.Parameters,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMetadata = `-- name: UpdateFileMetadata :exec
UPDATE file_metadata
SET
    last_parsed_at = ?,
    checksum = ?,
    updated_at = strftime('%s', 'now')
WHERE path = ?
`

type UpdateFileMetadataParams struct {
	LastParsedAt sql.NullInt64  `json:"last_parsed_at"`
	Checksum     sql.NullString `json:"checksum"`
	Path         string         `json:"path"`
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateFileMetadata, arg.LastParsedAt, arg.Checksum, arg.Path)
	return err
}

const updateSymbol = `-- name: UpdateSymbol :exec
UPDATE symbols
SET
    name = ?,
    type = ?,
    line = ?,
    column = ?,
    scope = ?,
    visibility = ?,
    return_type = ?,
    parameters = ?,
    parent_id = ?,
    updated_at = strftime('%s', 'now')
WHERE id = ?
`

type UpdateSymbolParams struct {
	Name       string         `json:"name"`
	Type       string         `json:"type"`
	Line       int64          `json:"line"`
	Column     int64          `json:"column"`
	Scope      sql.NullString `json:"scope"`
	Visibility sql.NullString `json:"visibility"`
	ReturnType sql.NullString `json:"return_type"`
	Parameters sql.NullString `json:"parameters"`
	ParentID   sql.NullString `json:"parent_id"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateSymbol(ctx context.Context, arg UpdateSymbolParams) error {
	_, err := q.db.ExecContext(ctx, updateSymbol,
		arg.Name,
		arg.Type,
		arg.Line,
		arg.Column,
		arg.Scope,
		arg.Visibility,
		arg.ReturnType,
		arg.Parameters,
		arg.ParentID,
		arg.ID,
	)
	return err
}
